repos:
-   repo: local
    hooks:
    -   id: codex-summary
        name: Regenerate Codex summary
        entry: python3 scripts/update_codex_summary.py
        language: system
        always_run: true
        pass_filenames: false